/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.redis;

import org.redis.scratchbook.Client;
import org.redis.scratchbook.Server;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
//        System.out.println(new App().getGreeting());
        try (Server server = new Server(9000)) { }
    }
}
